# Generated by Django 4.2.30 on 2026-08-02 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pageview', '页面访问'), ('click', '点击'), ('action', '功能操作'), ('error', '错误')], default='action', max_length=20, verbose_name='事件类型')),
                ('event_name', models.CharField(db_index=True, max_length=100, verbose_name='事件名称')),
                ('page_url', models.CharField(blank=True, default='', max_length=500, verbose_name='页面地址')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='会话')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='UA')),
                ('referrer', models.CharField(blank=True, default='', max_length=500, verbose_name='来源')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='自定义参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '埋点事件',
                'verbose_name_plural': '埋点事件',
                'db_table': 'analytics_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
