# Generated by Django 4.2.30 on 2026-08-01 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_conversation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('transport', models.CharField(choices=[('stdio', 'STDIO（本地进程）'), ('sse', 'SSE（Server-Sent Events）'), ('streamable_http', 'Streamable HTTP')], default='stdio', max_length=20, verbose_name='传输方式')),
                ('command', models.CharField(blank=True, default='', help_text='STDIO 模式：可执行文件路径，如 npx -y @modelcontextprotocol/server-filesystem /tmp', max_length=500, verbose_name='启动命令')),
                ('url', models.URLField(blank=True, default='', help_text='SSE/HTTP 模式：http://host:port/sse', max_length=500, verbose_name='服务地址')),
                ('env_vars', models.TextField(blank=True, default='', help_text='JSON 格式，如 {"API_KEY": "xxx"}', verbose_name='环境变量')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MCP 服务器',
                'verbose_name_plural': 'MCP 服务器',
                'db_table': 'mcp_server',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='McpTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='工具名称')),
                ('description', models.CharField(max_length=500, verbose_name='工具描述')),
                ('func_path', models.CharField(help_text='Python 模块路径，如 tools.ssh_utils.ssh_exec', max_length=500, verbose_name='函数路径')),
                ('parameters_schema', models.TextField(blank=True, default='', help_text='JSON Schema 格式，描述参数', verbose_name='参数 Schema')),
                ('category', models.CharField(choices=[('system', '系统运维'), ('database', '数据库'), ('network', '网络'), ('file', '文件'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='分类')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MCP 工具',
                'verbose_name_plural': 'MCP 工具',
                'db_table': 'mcp_tool',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill 名称')),
                ('description', models.CharField(max_length=500, verbose_name='描述')),
                ('icon', models.CharField(default='sparkles', help_text='Lucide 图标名，如 code, database, terminal, brain', max_length=50, verbose_name='图标')),
                ('color', models.CharField(choices=[('mint', '薄荷绿'), ('amber', '琥珀金'), ('blue', '蓝色'), ('purple', '紫色'), ('red', '红色'), ('pink', '粉色')], default='mint', max_length=20, verbose_name='主题色')),
                ('system_prompt', models.TextField(help_text='激活后会追加到 AI 的 system prompt 中', verbose_name='System Prompt 片段')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skill',
                'db_table': 'skill',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
