# Generated by Django 4.2.30 on 2026-08-07 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_mcpserver_mcptool_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '扫描中'), ('finished', '完成'), ('failed', '失败')], default='finished', max_length=20, verbose_name='状态')),
                ('source_type', models.CharField(choices=[('project', '当前项目'), ('path', '本地路径'), ('url', 'Git 仓库 URL')], default='project', max_length=20, verbose_name='目标类型')),
                ('target_path', models.CharField(blank=True, default='', max_length=1000, verbose_name='扫描目标')),
                ('files_scanned', models.IntegerField(default=0, verbose_name='扫描文件数')),
                ('findings_count', models.IntegerField(default=0, verbose_name='发现数')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
            ],
            options={
                'verbose_name': '扫描记录',
                'verbose_name_plural': '扫描记录',
                'db_table': 'secret_scan_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=100, verbose_name='规则ID')),
                ('rule_name', models.CharField(max_length=200, verbose_name='规则')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='级别')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件')),
                ('line_number', models.IntegerField(default=0, verbose_name='行号')),
                ('line_text', models.CharField(blank=True, default='', max_length=500, verbose_name='行内容')),
                ('secret_preview', models.CharField(max_length=200, verbose_name='脱敏密钥')),
                ('entropy', models.FloatField(default=0, verbose_name='熵值')),
                ('status', models.CharField(choices=[('open', '待处理'), ('false_positive', '误报'), ('fixed', '已修复')], default='open', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('scan_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='common.scanrun', verbose_name='所属扫描')),
            ],
            options={
                'verbose_name': '密钥发现',
                'verbose_name_plural': '密钥发现',
                'db_table': 'secret_finding',
                'ordering': ['-created_at', 'file_path', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pageview', '页面访问'), ('click', '点击'), ('action', '功能操作'), ('error', '错误')], default='action', max_length=20, verbose_name='事件类型')),
                ('event_name', models.CharField(db_index=True, max_length=100, verbose_name='事件名称')),
                ('page_url', models.CharField(blank=True, default='', max_length=500, verbose_name='页面地址')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='会话')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='UA')),
                ('referrer', models.CharField(blank=True, default='', max_length=500, verbose_name='来源')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='自定义参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '埋点事件',
                'verbose_name_plural': '埋点事件',
                'db_table': 'analytics_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
