# Generated by Django 4.2.30 on 2026-07-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DouyinHotSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('title', models.CharField(max_length=500, verbose_name='热搜标题')),
                ('hot_value', models.BigIntegerField(default=0, verbose_name='热度值')),
                ('label', models.CharField(default='normal', max_length=20, verbose_name='标签')),
                ('cover_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='封面图')),
                ('crawl_batch', models.DateTimeField(verbose_name='爬取批次时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '抖音热搜',
                'verbose_name_plural': '抖音热搜',
                'db_table': 'douyin_hot_search',
                'ordering': ['rank'],
            },
        ),
    ]
