# Generated by Django 4.2.30 on 2026-07-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务标识')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('func_path', models.CharField(max_length=500, verbose_name='执行函数路径')),
                ('cron_expr', models.CharField(default='0 * * * *', max_length=200, verbose_name='cron表达式')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('last_run_result', models.CharField(blank=True, default='', max_length=500, verbose_name='上次执行结果')),
                ('run_count', models.IntegerField(default=0, verbose_name='总执行次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '调度配置',
                'verbose_name_plural': '调度配置',
                'db_table': 'scheduler_config',
            },
        ),
    ]
