# Generated by Django 4.2.30 on 2026-08-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schedulerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboHotSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('title', models.CharField(max_length=500, verbose_name='热搜标题')),
                ('hot_value', models.BigIntegerField(default=0, verbose_name='热度值')),
                ('label', models.CharField(default='normal', max_length=20, verbose_name='标签')),
                ('url', models.URLField(blank=True, default='', max_length=2000, verbose_name='话题链接')),
                ('cover_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='封面图')),
                ('crawl_batch', models.DateTimeField(verbose_name='爬取批次时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '微博热搜',
                'verbose_name_plural': '微博热搜',
                'db_table': 'weibo_hot_search',
                'ordering': ['rank'],
            },
        ),
    ]
