# Generated by Django 4.2.30 on 2026-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weibohotsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinhotsearch',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2000, verbose_name='话题链接'),
        ),
    ]
