# Generated by Django 4.2.30 on 2026-08-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '扫描中'), ('finished', '完成'), ('failed', '失败')], default='finished', max_length=20, verbose_name='状态')),
                ('files_scanned', models.IntegerField(default=0, verbose_name='扫描文件数')),
                ('findings_count', models.IntegerField(default=0, verbose_name='发现数')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
            ],
            options={
                'verbose_name': '扫描记录',
                'verbose_name_plural': '扫描记录',
                'db_table': 'secret_scan_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=100, verbose_name='规则ID')),
                ('rule_name', models.CharField(max_length=200, verbose_name='规则')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='级别')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件')),
                ('line_number', models.IntegerField(default=0, verbose_name='行号')),
                ('line_text', models.CharField(blank=True, default='', max_length=500, verbose_name='行内容')),
                ('secret_preview', models.CharField(max_length=200, verbose_name='脱敏密钥')),
                ('entropy', models.FloatField(default=0, verbose_name='熵值')),
                ('status', models.CharField(choices=[('open', '待处理'), ('false_positive', '误报'), ('fixed', '已修复')], default='open', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('scan_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scanrun', verbose_name='所属扫描')),
            ],
            options={
                'verbose_name': '密钥发现',
                'verbose_name_plural': '密钥发现',
                'db_table': 'secret_finding',
                'ordering': ['-created_at', 'file_path', 'line_number'],
            },
        ),
    ]
