# Generated by Django 4.2.30 on 2026-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='source_type',
            field=models.CharField(choices=[('project', '当前项目'), ('path', '本地路径'), ('url', 'Git 仓库 URL')], default='project', max_length=20, verbose_name='目标类型'),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='target_path',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='扫描目标'),
        ),
    ]
