# Generated by Django 4.2.30 on 2026-08-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanrun_source_type_scanrun_target_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息'),
        ),
    ]
